version: '3.7'
services:
  redis:
    container_name: redis
    image: redis
    profiles: ['redis']
    command: redis-server
    ports:
      - '6379:6379'
    expose:
      - '6379'
    restart: always

  api:
    container_name: api
    environment:
      REDIS_URL: redis://redis:6379
    profiles: ['redis', 'inmemory']
    build: api/
    restart: always
    ports:
      - '8080:8080'

  frontend:
    container_name: frontend
    profiles: ['redis', 'inmemory']
    build: frontend/
    restart: always
    ports:
      - '3000:3000'
