version: '3.7'
services:
  mysql:
    container_name: mysql
    image: mysql
    hostname: mysql
    ports:
      - '3307:3306'
    expose:
      - '3306'
    restart: always

  redis:
    container_name: redis
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
    expose:
      - '6379'
    restart: always

  api:
    container_name: api
    environment:
      REDIS_URL: redis://redis:6379
      MYSQL_HOST: host.docker.internal
    build: api/
    restart: always
    ports:
      - '8080:8080'

  frontend:
    container_name: frontend
    build: frontend/
    restart: always
    ports:
      - '3000:3000'
